services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.SXNG.${HASH}.rule=Host(`${PERPLEXICA_SXNG_HOST}`)"
      - "traefik.http.services.SXNG.${HASH}.loadbalancer.server.port=${PERPLEXICA_SXNG_PORT}"
      - "traefik.http.routers.SXNG.${HASH}.entrypoints=websecure"
      #- "traefik.http.routers.SXNG.${HASH}.entrypoints=web"
      - "traefik.http.routers.SXNG.${HASH}.tls.certResolver=letsencrypt"

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/perplexica/data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.BE.${HASH}.rule=Host(`${PERPLEXICA_HOST}`)"
      - "traefik.http.services.BE.${HASH}.loadbalancer.server.port=${PERPLEXICA_BE_PORT}"
      - "traefik.http.routers.BE.${HASH}.entrypoints=websecure"
      #- "traefik.http.routers.BE.${HASH}.entrypoints=web"
      - "traefik.http.routers.BE.${HASH}.tls.certResolver=letsencrypt"

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:3001/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
    depends_on:
      - perplexica-backend
    ports:
      - 3000:3000
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.FE.${HASH}.rule=Host(`${PERPLEXICA_HOST}`)"
      - "traefik.http.services.FE.${HASH}.loadbalancer.server.port=${PERPLEXICA_FE_PORT}"
      - "traefik.http.routers.FE.${HASH}.entrypoints=websecure"
      #- "traefik.http.routers.FE.${HASH}.entrypoints=web"
      - "traefik.http.routers.FE.${HASH}.tls.certResolver=letsencrypt"

networks:
  dokploy-network:
    external: true

volumes:
  backend-dbstore:
